name: sync-release

on:
  workflow_dispatch:
    inputs:
      tag:   
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false   
      - name: sync release
        uses: kanzihuang/mirror-release-action@v1
        with:
          repository: coodesker/coodesker-desktop
          tag: v1.0.4.1
          patterns: C*.exe
